### ISSUE TITLE
Inputs on the first checkout step are not visible in case of custom modification

### ISSUE THREAD

**Issue by PandaTawer** [avarda-ab/Magento-2-Checkout-3-module#22] opened 2022-09-21 08:36 UTC
If we want to show some extra inputs they will be disabled in this case

https://github.com/avarda-ab/Magento-2-Checkout-3-module/blob/6b9200b4abdabab05f21c0d5c8570b8df3a5c536/view/frontend/web/js/view/shipping-method.js#L76

The possible solution is to disable false to all inputs on the first checkout step.
Example of code.
`$('#checkout-step-postalcode').find(':input').attr('disabled', false);`

**Comment by PandaTawer** [comment] 2022-09-23 13:20
Also, it'll be good to enable this class `.block-authentication` to prevent disabled inputs in the login modal.

**Comment by juhanihaapala** [comment] 2022-09-29 09:13
Good catch, I'll change this in next release.

**Comment by juhanihaapala** [comment] 2022-11-16 06:56
This is now fixed in latest release. 

And actually the temporary fix didn't work anymore with latest magento (2.4.5-p1) so I digged the root cause of this and it was actually the block-loader which was disabling inputs while the loader was visible, but there was other loaders already so I removed the block-loader altogether.

**Closed by juhanihaapala** 2022-11-16 06:56 UTC
Labels: bug

**Comment by juhanihaapala** [comment] 2022-11-18 12:19
Actually the error was still persistent in pre 2.4.5-p1 versions, but is now fixed to work also with older magento versions in latest version [v1.3.4](https://github.com/avarda-ab/Magento-2-Checkout-3-module/releases/tag/1.3.4)
